apiVersion: v1
kind: Service
metadata:
  name: java-micro-one-postgres
  labels:
    app: java-micro-one
    service: postgres
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 5432
     targetPort: 5432
     name: postgres
  selector:
    app: java-micro-one
    service: postgres
